#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while read -r name
do
   echo "$name" | cut -d ":" -f1,4,6
done < /etc/passwd
